# **STRING FORMATTING 28th Febraury 2026**

String formatting is essential for creating readable and well structured output in python programs. It allows us to combine text and variables seamlessly

In [ ]:
# use of str(), to combine texts
name = 'Rebecca'
age = 26
print('My name is ' + str(name) + '. I am ' + str(age) + ' years old')

My name is Rebecca. I am 26 years old

In [ ]:
# use of functions to combine texts
print(f"My name is {name}. I am {age} years old")

My name is Rebecca. I am 26 years old

In [ ]:
# .format()
print('My name is {0}. I am {1} years old'.format(name,age))

My name is Rebecca. I am 26 years old

IF STATEMENTS

In [ ]:
# if statements
x = 20
if x>0 and x%2 == 0:
  print('x is greater than zero')

x is greater than zero

In [ ]:
# if statements
x  = 10
if x >0 and x % 2 == 0:
  print('x is not an odd number')

x is not an odd number

An if-else statement is used when you want a program to make a decision and execute different statements depending on whether a condition is true or false.

else statement and nested if

In [ ]:
# else statement
x =int(input('Enter a number:'))
if x > 0 and x%2== 0:
  print('x is an even number')
else:
  print('x is an odder number')

Enter a number:25
x is an odder number

In [ ]:
# else statement
y = int(input('Enter any number of your choice: '))
if  y > 0 and y % 3 ==0:
  print('The number is positive and divisible by 3')
else:
  print('The number does not meet the conditions')

Enter any number of your choice: 20
The number does not meet the conditions

In [ ]:
# nested if
age= 14
if age>18:
  if age <21:
    print('You are an adult, but not allowed to drink')
  else:
    print('You are an adult and allowed to drink')
else:
  print('You are underage')

You are underage

In [ ]:
# nested if
score = int(input(' Enter your Exam score: '))
if score >= 50:
  if score >= 75:
   print('You passed with Distinction')
  else:
    print('You Passed')
else:
 print('You failed the exam')

 Enter your Exam score: 76
You passed with Distinction

# if elif else

In [ ]:
# if elif else
age= 17
if age>= 18 and age< 21:
  print('You are an adult but not allowed to drink yet')
elif age>=18 and age>=21:
  print('You are an adult and allowed to drink')
else:
  print('You are underage')

You are underage

In [ ]:
# if elif else
score = int(input('Enter the student score: '))
if score >= 90:
  print('A')
elif score>=80:
  print('B')
elif score >=70:
  print('C')
elif score >60:
  print('D')
elif score >50:
  print('E')
else:
  print('Failed')

Enter the student score: 55
E

Tenary operators

In [ ]:
# Tenary operators, It is a concise way to express a conditional statement
num = 10
result= 'Positive' if num >0 else 'Negative'
print(result)

Positive

In [ ]:
age = int(input('Enter your age: '))
category= 'Adult' if age > 18 else 'Child'
print(category)

Enter your age: 26
Adult

In [ ]:
x = 18
result = 'even' if x % 2 == 0 else 'odd'
print(result)

even

#Loops 1st march 2026

For loops are used to iterate over a sequence such as a list, tuple or string and execute a block of code for each element in the sequence

Syntax:
for item interable:

In [ ]:
#  Code block to excute for each

In [ ]:
# iterating over a list
fruits= ['apple','mangoes','lemon']
for items in fruits:
  print(items)

apple
mangoes
lemon

In [ ]:
# iterating over a list to print an odd number
number = [1,2,3,4,5,6,7,8,9,10]
for i in number:
  if i % 2 == 1:
    print(i)

1
3
5
7
9

In [ ]:
# iterating over a dictionary
person = {'name': 'Rebecca', 'age': 26, 'city': 'Kampala'}
for key, value in person.items():
  print(f'{key},{value}')

name,Rebecca
age,26
city,Kampala

In [ ]:
# iterating to get sum
list_ = [20,30,40,50,60,70,80]
total = 0
for item in list_:
  total += item
print(total)

350

In [ ]:
# iterating to get product
list_=[1,2,3,4]
product = 3
for item in list_:
  product *= item
print(product)

72

While Loop

While loops repeatedly execute a block of code as long as a specified condition is True

While codition: code block to execute while condition is true

In [ ]:
# looping and printing a value
x = 1
while x <= 5:
  print(x)
  x += 1

1
2
3
4
5

In [ ]:
# looping and printing a value
x = 1
while x <= 16:
    print(x)
    x *= 2

1
2
4
8
16

In [ ]:
# looping over a list and printing the items in the list
fruit = ['managoes','pine apple','orange']
x = 0
while x <= 2:
  print(fruit[x])
  x += 1

managoes
pine apple
orange

In [ ]:
name = ['Mercy','Sharon','Rebecca','Flavia']
x = 0
while x <= 3:
  print(name[x])
  x +=1

Mercy
Sharon
Rebecca
Flavia

In [ ]:
# Looping over a dictionary and printing  each key value pair
my_dict = {'a': 1, 'b': 2, 'c':3}
keys = list(my_dict.keys()) # convert dictionary keys to list for indexing
index = 0
while index < len(keys):
  key = keys[index]
  value = my_dict[key]
  print(f'{key}: {value}')
  index += 1

a: 1
b: 2
c: 3

In [ ]:
# calculating the sum of numbers in a list using a while loop
numbers =[1,2,3,4,5]
total =0
index= 0
while index<len(numbers):
  total +=number[index]
  index +=1
print('sum of number:', total)

sum of number: 350

Functions

Functions are blocks of reusuable code that perform a specific task. They help in organizing code, promoting reusability and improving readability

Syntax: def function_name(parameters)

In [ ]:
def add(num_1, cheddar):
  new_force = num_1 +cheddar
  return new_force

In [ ]:
add(2,4)

6

In [ ]:
def f(x,y):
  function = (x+y)*x
  return function

In [ ]:
f(2,4)

12

In [ ]:
# Function to greet the user
def greet(name):
  """Greets the user"""
  return f"Hello, {name}!"

message= greet('Rebecca')
print(message)

Hello, Rebecca!

In [ ]:
#Function to return the sum and product of two numbers
def sum_and_product(a,b):
  return a+b, a*b

  result = sum_and_product(a,b)
  print('sum:', result[0])
  print('product:',result[1])

In [ ]:
sum_and_product(2,4)

(6, 8)

Lambda Functions:

Lambda Functions, also known as anonymous functions, are small, single expressions that can be defined in line using the lambda key word

They are useful for creating quick, throwaway functions without the need for a formal def statement

In [ ]:
# Adding the numbers
add =  lambda x,y: x+y
print(add(2,6))

8

In [ ]:
# Getting the product of numbers
product = lambda x,y: x*y
print(product(4,6))

24

In [ ]:
students =[
    {'name': 'Alice', 'grade': 85},
    {'name': 'Bob', 'grade': 92},
]
sorted_students = sorted(students, key=lambda student: student['grade'],reverse=True)
print(sorted_students)

[{'name': 'Bob', 'grade': 92}, {'name': 'Alice', 'grade': 85}]

Built in Functions

Python comes with several built in functions that perform common operations efficiently

map(function,iterable):

In [ ]:
# Finding the square of the numbers in the list
numbers=[1,2,3,4,5]
squared= map(lambda x: x**2, numbers)
print(list(squared))

[1, 4, 9, 16, 25]

In [ ]:
# coverting temperatures from celsius to Fahrenheit using map
temps_celsius= [0,10,20,30]
temps_fahrenheit = map(lambda c: (c*9/5)+32, temps_celsius)
print(list(temps_fahrenheit))

[32.0, 50.0, 68.0, 86.0]

In [ ]:
# Capitalizing the first letter of each word in alist of strings using map
words=['hello','world']
capitilized_words = map(lambda w: w.capitalize(), words)
print(list(capitilized_words))

['Hello', 'World']

filter(function, iterable): Filters elements from an iterable based on the given function's truthiness

In [ ]:
# finding the even numbers in the list
numbers= [1,2,3,4,5,6]
evens =  filter(lambda x: x%2 ==0, numbers)
print(list(evens))

[2, 4, 6]

In [ ]:
# finding negative numbers in a list
number = [1, -2,3,-6,4]
negative_numbers= filter(lambda x: x<0, number)
print(list(negative_numbers))

[-2, -6]

In [ ]:
# finding positive numbers in a list
number = [1, -2,3,-6,4]
positive_numbers= filter(lambda x: x>0, number)
print(list(positive_numbers))

[1, 3, 4]

reduce(function,iterable[,initializer]):

Applies the given function cumulatively to the items of the iterable, from left to right , to reduce the iterable to a single value

In [ ]:
# Finding the product of the elements in the list
from functools import reduce
numbers =[1,2,3,4,5]
product = reduce(lambda x,y: x*y, numbers)
print(product)

120

In [ ]:
#finding the maximum element in alist using reduce
numbers = [1,2,3,4,5]
max_num = reduce(lambda x,y: x if x>y else y, numbers)
print(max_num)

5

In [ ]:
#finding the maximum element in alist using reduce
numbers= [29,2,3,40,87]
max_num= reduce(lambda x,y: x if x>y else y, numbers)
print(max_num)

87

sum(iterable[,start]):

Returns the sum of all elements in the iteration

In [ ]:
# finding the sum of the numbers in the list
numbers= [1,2,3,4]
total = sum(numbers)
print(total)

10

max(iterable[,key,default])

Returns the maximum element from the iteration

In [ ]:
#finding the maximum value in a lis
numbers= [2,4,6,7,50,9]
max_num= max(numbers)
print(max_num)

50

In [ ]:
# finding the longest string in alist
strings= ['apple','banana','cherry']
longest_string= max(strings, key=len)
print(longest_string)

banana

min(iterable[,key,default])

returns the minimum element from the iterable

In [ ]:
#finding the minimum element from iterable
numbers= [1,2,3,4,5]
min_num= min(numbers)
print(min_num)

1

In [ ]:
# finding the minimum value in a dictionary
scores= {'Rebecca':90,'Mercy':76}
min_score= min(scores.values())
print(min_score)

76

# Pandas

Pandas is a powerful python library for data manipulation and anlaysis . It provides two primary data structures: series and Dataframe

How to install: pip install pandas

Series is a one dimensional labeled array of holding any data type . it is similar to a one dimensional Numpy array but with additional functionality and a labeled index

In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,'Rebecca',9,10])
print(s)

0          1
1          2
2          3
3          4
4    Rebecca
5          9
6         10
dtype: object

DataFrameis a two dimensional labeled data structure with columns of potentially different data types. it is similar to a spread sheet or SQL table

In [ ]:
# creating a DataFrame from a dictionary
df={'name' :['Rebecca','Sharon','Mirriam'],
    'age' : [24,27,22],
    'location': ['Lira','Kampala','Nakuru']
    }
data = pd.DataFrame(df)
print(data)

      name  age location
0  Rebecca   24     Lira
1   Sharon   27  Kampala
2  Mirriam   22   Nakuru

Data Manipulation

Indexing and slicing: We can access and manipulate data in Series and DataFrame usinxg indexing and slicing

In [ ]:
# Access elements in a  Series
print(s[0])

1

In [ ]:
# Access elements in a column / slicing a DataFrame
data['name']

0    Rebecca
1     Sharon
2    Mirriam
Name: name, dtype: object

Data Combination

Is the process of joining, merging or concatenating multiple pandas data structure in to a single data structure.
The most common ways of combining Dataframes are concatenation, joining and merge

Concatenation

```
This is formatted as code: using concat function to combine two or more dataframes with the same columns either vertically or horizontally
```

if they don't have the same column, we can't concatenate

In [ ]:
df_1= pd.DataFrame({'A':[2,4,6],'B':['x','y','z']})
df_2= pd.DataFrame({'A':[20,20,5],'B':['w','v','u']})

In [ ]:
df_1

   A  B
0  2  x
1  4  y
2  6  z

In [ ]:
df_2

    A  B
0  20  w
1  20  v
2   5  u

In [ ]:
# vertical concatenation (row wise), axis=0 represents vertical concatenation
vertical_com = pd.concat([df_1,df_2], axis=0, keys=['df_1','df_2'])
vertical_com

         A  B
df_1 0   2  x
     1   4  y
     2   6  z
df_2 0  20  w
     1  20  v
     2   5  u

In [ ]:
vertical_com.loc["df_1"]

   A  B
0  2  x
1  4  y
2  6  z

In [ ]:
vertical_com.loc["df_1",0]

A    2
B    x
Name: (df_1, 0), dtype: object

In [ ]:
vertical_com.loc["df_1",0][0]

/tmp/ipykernel_303/2645724590.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vertical_com.loc["df_1",0][0]

np.int64(2)

In [ ]:
vertical_com.loc["df_1",0]["A":"B"]

A    2
B    x
Name: (df_1, 0), dtype: object

In [ ]:
# Vertical concatenation (row-wise)
vertical_com = pd.concat([df_1, df_2], axis=0, ignore_index=True)
vertical_com

    A  B
0   2  x
1   4  y
2   6  z
3  20  w
4  20  v
5   5  u

In [ ]:
# Horizontal concatenation (column-wise)
horizontal_com = pd.concat([df_1, df_2], axis=1, keys=["df_1","df_2"])
horizontal_com

  df_1    df_2
     A  B    A  B
0    2  x   20  w
1    4  y   20  v
2    6  z    5  u

In [ ]:
horizontal_com["df_1"]

   A  B
0  2  x
1  4  y
2  6  z

In [ ]:
horizontal_com["df_2"]

    A  B
0  20  w
1  20  v
2   5  u

In [ ]:
horizontal_com["df_1"][["A","B"]]

   A  B
0  2  x
1  4  y
2  6  z

In [ ]:
data_team = pd.DataFrame({'name':['Rebecca','James'],
                         'Position':['Data Analyst','Junior Data Analyst'],
                         'Duty station':['Kampala','Soroti']})
recovery_team = pd.DataFrame({'name':['Keneth','Henry'],
                         'Position':['Senior Recovery Officer','Recovery Officer'],
                         'Duty station':['Lira','Adjumani']})
df_3 = pd.concat([data_team,recovery_team], ignore_index=True)
df_3

      name                 Position Duty station
0  Rebecca             Data Analyst      Kampala
1    James      Junior Data Analyst       Soroti
2   Keneth  Senior Recovery Officer         Lira
3    Henry         Recovery Officer     Adjumani

In [181]:
df_4 = pd.DataFrame({'Windspeed':[8,5,7,8,6,4,9,10,5]})
df_4

   Windspeed
0          8
1          5
2          7
3          8
4          6
5          4
6          9
7         10
8          5

In [184]:
# axis =0, adds the row below where the first dataframe records ended
pd.concat([df_3,df_4], ignore_index=True, axis=0)

       name                 Position Duty station  Windspeed
0   Rebecca             Data Analyst      Kampala        NaN
1     James      Junior Data Analyst       Soroti        NaN
2    Keneth  Senior Recovery Officer         Lira        NaN
3     Henry         Recovery Officer     Adjumani        NaN
4       NaN                      NaN          NaN        8.0
5       NaN                      NaN          NaN        5.0
6       NaN                      NaN          NaN        7.0
7       NaN                      NaN          NaN        8.0
8       NaN                      NaN          NaN        6.0
9       NaN                      NaN          NaN        4.0
10      NaN                      NaN          NaN        9.0
11      NaN                      NaN          NaN       10.0
12      NaN                      NaN          NaN        5.0